print('Simple Calculator')
x=int(input("Enter value for x ="))
y=int(input("Enter value for y ="))
print('The Addition of two numbers is')
print(x+y)
print('The Subtraction of two numbers is')
print(x-y)
print('The Multiplication of two numbers is')
print(x*y)
print('The Division of two numbers is')
print(x/y)
print('The Modulus of two numbers is')
print(x%y)
print('The Exponent of two numbers is')
print(x**y)
print('The Floor Division of two numbers is')
print(x//y)
